Use testmon for tests and add coverage summary in test workflow instead of separate workflow (resolving permission issues)

diff --git a/.github/workflows/django-migration-test.yml b/.github/workflows/django-migration-test.yml
--- a/.github/workflows/django-migration-test.yml
+++ b/.github/workflows/django-migration-test.yml
@@ -1,4 +1,4 @@
-name: Django Tests with Migration Check and Coverage
+name: Django Migration Check
 
 on:
   workflow_call:
@@ -13,32 +13,32 @@ on:
       postgres_host:
         type: string
         required: true
+      # Provided by caller workflow
+      python_version:
+        type: string
+        required: true
+      poetry_version:
+        type: string
+        required: true
       # Optional
-      python_versions:
-        type: string
-        description: A JSON string list of all python versions to run these tests on
-        default: "['3.11.2']"
-      poetry_versions:
-        type: string
-        description: A JSON string list of all python versions to run these tests on
-        default: "['1.8.4']"
       working_directory:
         type: string
-        description: Whenever the django app (i.e. manage.py) is not in the root; the location can be specified here
-        default: .
+        description: Whenever the django app (i.e. manage.py) is not in the root; the location can be specified here. The last slash needs to be included
+        default: ./
     secrets:
       postgres_password:
+        required: true
+      private_pypi_url:
+        required: true
+      private_pypi_user:
+        required: true
+      private_pypi_password:
         required: true
 
 jobs:
   test-migrations:
-    name: Django Tests With Postgres and Coverage for python version ${{ matrix.python.version }}
-    strategy:
-      matrix:
-        python-version: ${{ fromJSON(inputs.python_versions) }}
-        poetry-version: ${{ fromJSON(inputs.poetry_versions) }}
-      runs-on: ubuntu-latest
-      container: python:${{ matrix.python-version }}-alpine
+    name: Django Migration Check
+    runs-on: ubuntu-latest
 
     services:
       # This service requires that variables and secrets are defined on GitHub (see README)
@@ -61,30 +61,48 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Install needed apk packages
-        run: apk update && apk add bash && apk add zstd && apk add tar
+      - name: Setup python ${{ inputs.python_version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ inputs.python_version }}
 
       - name: Load cache
         id: cache
         uses: actions/cache@v4
         with:
           path: |
-            ${{ inputs.working_directory }}/.venv
-            /github/home/.local
-          key: cache-poetry-${{ matrix.poetry_version }}-python-${{ matrix.python_version }}--${{ hashFiles('**/poetry.lock') }}
+            ${{ inputs.working_directory }}.venv
+            /home/runner/.local/
+          key: cache-python-${{ inputs.python_version }}-poetry-${{ inputs.poetry_version }}-${{ hashFiles('**/poetry.lock') }}
 
-      - name: Add cache to path
-        if: steps.cache.outputs.cache-hit == 'true'
-        run: echo "/github/home/.local/bin" >> $GITHUB_PATH
-
-      - name: Install Poetry V${{ matrix.poetry_version }}
+      - name: Install Poetry
         if: steps.cache.outputs.cache-hit != 'true'
         uses: snok/install-poetry@v1
         with:
-          version: ${{ matrix.poetry_version }}
+          version: 1.8.4
           virtualenvs-create: true
           virtualenvs-in-project: true
           installer-parallel: true
+
+      - name: Check Poetry
+        working-directory: ${{ inputs.working_directory }}
+        run: |
+          INSTALL_MSG=$(poetry install --dry-run 2>&1 | tail -1)
+          if [[ "$INSTALL_MSG" != '' ]]; then
+            echo "<h2>:no_entry_sign: Poetry install dry-run failed </h2>" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
+            exit 3
+          fi
+
+      - name: Configure Poetry and install packages
+        working-directory: ${{ inputs.working_directory }}
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          poetry config repositories.repowered ${{ secrets.private_pypi_url}}
+          poetry config http-basic.repowered ${{ secrets.private_pypi_user }} ${{ secrets.private_pypi_password}}
+          poetry install --no-interaction --no-root --no-ansi
 
       - name: Check Django Migrations
         working-directory: ${{ inputs.working_directory }}
